# 이름 설정
name: ChatBot Dev CI/CD

# on: 실행 트리거 역할 : 언제 이 작업을 수행할 것인가
# main 브랜치에 push하면 CI/CD 실행
on:
  push:
    branches:
      - main
# 작업 환경 설정
jobs:
  Deploy:
    runs-on: ubuntu-latest # 해당 환경을 실행할 운영체제 지정
    steps:
      - name: SSH로 EC2에 원격 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script: |
            cd /home/ubuntu/NoticeChatbot
            git pull origin main
            ./gradlew clean build 
            sudo fuser -f -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
